CREATE TABLE CARS (
    CAR_ID SERIAL PRIMARY KEY,
    MANUFACTURER TEXT,
    MODEL_NAME TEXT,
    MODEL_VARIANT TEXT,
    SERIAL_NUMBER TEXT,
    WEIGHT NUMERIC,
    ENGINE_CC NUMERIC,
    PRICE NUMERIC
);

CREATE TABLE SALESPERSON (
    SALESPERSON_ID SERIAL PRIMARY KEY,
    NAME TEXT,
    CONTACT TEXT
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    NAME TEXT,
    CONTACT TEXT
);

CREATE TABLE TRANSACTION (
    TRANSACTION_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT,
    SALESPERSON_ID INT,
    CAR_ID INT,
    TIME_SOLD TIMESTAMP,
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_SALESPERSON FOREIGN KEY (SALESPERSON_ID) REFERENCES SALESPERSON(SALESPERSON_ID),
    CONSTRAINT FK_CAR FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID)
);